version: '3.9'
services:
  edcb-wine:
    image: edcb-wine
    container_name: EDCB-Wine
    build:
      context: .
    # OS 起動時にコンテナを自動起動する
    restart: always
    # ネットワークをホスト側と共有する
    # 標準の bridge モード (仮想ネットワーク) だと localhost との通信が面倒
    network_mode: host
    # Xfce のデスクトップ環境はなぜか特権モードでないと正常に動作しない
    privileged: true
    # ボリュームのマウント設定
    # /host-rootfs/ はコンテナ内の EDCB からホストマシン上のファイルを読み書きするために必要
    volumes:
      - type: bind
        source: './EDCB/'
        target: '/EDCB/'
      - type: bind
        source: '/'
        target: '/host-rootfs/'
